export const API_VERSION_NOT_PROVIDED = 'API VERSION MUST BE INCLUDED';

export const AUTH_OAUTH_ERR_GOOGLE = { code: 'ATH_GOO_001', msg: 'AUTH OAUTH ERROR GOOGLE' };
export const AUTH_OAUTH_ERR_GOOGLE_FAILED_TOKEN_FETCH = { code: 'ATH_GOO_002', msg: 'FAILED TO FETCH TOKEN' };

export const AUTH_REGISTER_OAUTH_NO_EMAIL = { code: 'ATHR_REG_OTH_001', msg: 'MISSING EMAIL' };

export const AUTH_REGISTER_ALREADY_REGISTERED = { code: 'ATHR_REG_001', msg: 'ACCOUNT WITH EMAIL ALREADY EXISTS' };

export default '';
